services:
  kafka:
    container_name: kafka
    image: apache/kafka-native:latest
    ports:
    - 9092:9092
    environment:
      # Broker configuration see https://kafka.apache.org/documentation/#brokerconfigs
      # configuration of listeners (list of URLs to listen on) including listener names
      # 9092 for host communication, 9093 for internal docker network communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      # listeners to publish for clients to use
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      # mapping between listener names and security protocols
      # PLAINTEXT protocol, standard protocol, for unencrypted traffic
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      # broker id for this server
      KAFKA_NODE_ID: 1
      # roles, that process plays,
      KAFKA_PROCESS_ROLES: broker,controller
      # names of listener used by the controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # mapping of id@host:port form the set of voters
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # required for a single node cluster
      # replication factor for the offsets topic, internal topic (set higher to ensure availability)
      # Internal topic creation will fail until the cluster size meets this replication factor requirement
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # replication factor for the transaction topic, internal topic (set higher to ensure availability)
      # internal topic creation will fail until the cluster size meets this replication factor requirement
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # minimum number of replicas that must acknowledge a write to transaction topic in order to be considered successful
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # default number of log partitions per topic
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
    - 8080:8080
    environment:
      # enabling dynamic configuration of Kafka clusters
      DYNAMIC_CONFIG_ENABLED: true
      # displayed cluster name
      KAFKA_CLUSTERS_0_NAME: local
      # connection to Kafka cluster via internal docker network, see KAFKA_ADVERTISED_LISTENERS in kafka service 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
    # making sure, kafka service has started bevore starting kafka-ui service
    - kafka
  
  schema-registry:
    image: docker.io/bitnami/schema-registry:latest
    ports:
    - 8081:8081
    environment:
    # listeners to publish for clients to use
    - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    # connection to Kafka cluster via internal docker network, see KAFKA_ADVERTISED_LISTENERS in kafka service 
    - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9093
    depends_on:
    # making sure, kafka service has started bevore starting schema-registry service
    - kafka