# Generated by Django 4.2.17 on 2025-01-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kafka_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
