# Generated by Django 4.2.17 on 2025-01-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0002_alter_job_kafka_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_handler.agent'),
        ),
    ]
