# Generated by Django 4.2.17 on 2025-01-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0004_remove_job_container_memory_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='container_cpu_limit',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='job',
            name='container_memory_limit_in_mb',
            field=models.IntegerField(default=512),
        ),
    ]
