# Generated by Django 4.2.17 on 2025-01-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0005_alter_job_container_cpu_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='iot_data_kafka_topic',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
