# Generated by Django 4.2.17 on 2025-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0006_job_iot_data_kafka_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='This is an example description of the job', max_length=500),
            preserve_default=False,
        ),
    ]
