# Generated by Django 4.2.17 on 2025-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0007_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='docker_agent_id',
            field=models.CharField(default='placeholder_id', max_length=200),
            preserve_default=False,
        ),
    ]
