# Generated by Django 4.2.17 on 2025-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0008_agent_docker_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='docker_container_id',
            field=models.CharField(default='placeholder_id', max_length=200),
            preserve_default=False,
        ),
    ]
