# Generated by Django 4.2.17 on 2025-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_handler', '0009_container_docker_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('deploying', 'Deploying'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=10),
        ),
    ]
