services:
  kafka:
    container_name: kafka
    image: apache/kafka-native:latest
    ports:
    - 9092:9092
    environment:
      # Broker configuration see https://kafka.apache.org/documentation/#brokerconfigs
      # configuration of listeners (list of URLs to listen on) including listener names
      # 9092 for host communication, 9093 for internal docker network communication
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      # listeners to publish for clients to use
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      # mapping between listener names and security protocols
      # PLAINTEXT protocol, standard protocol, for unencrypted traffic
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # broker id for this server
      KAFKA_NODE_ID: 1
      # roles, that process plays,
      KAFKA_PROCESS_ROLES: broker,controller
      # names of listener used by the controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # mapping of id@host:port form the set of voters
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      # listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # required for a single node cluster
      # replication factor for the offsets topic, internal topic (set higher to ensure availability)
      # Internal topic creation will fail until the cluster size meets this replication factor requirement
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # replication factor for the transaction topic, internal topic (set higher to ensure availability)
      # internal topic creation will fail until the cluster size meets this replication factor requirement
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # minimum number of replicas that must acknowledge a write to transaction topic in order to be considered successful
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # default number of partitions per topic
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
    - 8080:8080
    environment:
      # enabling dynamic configuration of Kafka clusters
      DYNAMIC_CONFIG_ENABLED: true
      # displayed cluster name
      KAFKA_CLUSTERS_0_NAME: local
      # connection to Kafka cluster via internal docker network, see KAFKA_ADVERTISED_LISTENERS in kafka service 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
    # making sure, kafka service has started bevore starting kafka-ui service
    - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
    - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      # connection to Kafka cluster via internal docker network, see KAFKA_ADVERTISED_LISTENERS in kafka service 
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9093
      # listeners to publish for clients to use
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
    # making sure, kafka service has started bevore starting schema-registry service
    - kafka

  initializer:
    image: python:3.13-slim
    container_name: initializer
    volumes:
    - ./initialize.py:/tmp/initialize.py
    working_dir: /tmp
    # set -e to make sure that in the case of an error, exit
    entrypoint: ['sh', '-c', 'set -e; pip install confluent-kafka && python initialize.py']
    depends_on:
    # making sure, kafka service has started bevore starting initializer service
    - kafka